from card import Card, Suit, Rank

_ACE_OF_SPADES = Card(Suit.SPADES, Rank.ACE)
_SEVEN_OF_SPADES = Card(Suit.SPADES, Rank.SEVEN)
_TWO_OF_SPADES = Card(Suit.SPADES, Rank.TWO)


_ACE_OF_CLUBS = Card(Suit.CLUBS, Rank.ACE)
_KING_OF_CLUBS = Card(Suit.CLUBS, Rank.KING)
_QUEEN_OF_CLUBS = Card(Suit.CLUBS, Rank.QUEEN)
_SEVEN_OF_CLUBS = Card(Suit.CLUBS, Rank.SEVEN)
_THREE_OF_CLUBS = Card(Suit.CLUBS, Rank.THREE)

_ACE_OF_HEARTS = Card(Suit.HEARTS, Rank.ACE)
_SEVEN_OF_HEARTS = Card(Suit.HEARTS, Rank.SEVEN)
_FOUR_OF_HEARTS = Card(Suit.HEARTS, Rank.FOUR)
_TWO_OF_HEARTS = Card(Suit.HEARTS, Rank.TWO)

_ACE_OF_DIAMONDS = Card(Suit.DIAMONDS, Rank.ACE)
_KING_OF_DIAMONDS = Card(Suit.DIAMONDS, Rank.KING)
_JACK_OF_DIAMONDS = Card(Suit.DIAMONDS, Rank.JACK)
_QUEEN_OF_DIAMONDS = Card(Suit.DIAMONDS, Rank.QUEEN)
